# Disable sudo to speed up the build
sudo: false

language: python

# python versions to test
python:
  - "3.7.4"
  - "3.7-dev"
  - "3.8"

# test with pytest
script:
  - pytest

# install dependencies
install:
  - pip install typing_extensions
  - pip install codecov
  - pip install pytest pytest-cov

# run the unit test
script:
  - pytest --cov=./typing_json/

# push the results back to codecov
after_success:
  - codecov
